# Generated by Django 5.2.8 on 2025-11-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('km_jud', models.IntegerField(default=0)),
                ('km_nat', models.IntegerField(default=0)),
                ('km_euro', models.IntegerField(default=0)),
                ('km_auto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lat', 'lon'), name='unique_lat_lon')],
            },
        ),
        migrations.CreateModel(
            name='EnergyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.point')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('wind_rose', models.JSONField(blank=True, default=dict)),
                ('rating', models.IntegerField(default=0)),
                ('avg_potential', models.FloatField(default=0.0)),
                ('infrastructure_rating', models.FloatField(default=0.0)),
                ('index_average', models.FloatField(default=0.0)),
                ('A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_A', to='analysis.point')),
                ('B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_B', to='analysis.point')),
                ('C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_C', to='analysis.point')),
                ('D', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_D', to='analysis.point')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_center', to='analysis.point')),
                ('closest_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.energystorage')),
            ],
        ),
        migrations.CreateModel(
            name='RegionGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_km', models.FloatField()),
                ('zones_per_edge', models.IntegerField()),
                ('A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_A', to='analysis.point')),
                ('B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_B', to='analysis.point')),
                ('C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_C', to='analysis.point')),
                ('D', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_D', to='analysis.point')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='analysis.region')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_direction', models.FloatField(default=0.0)),
                ('avg_wind_speed', models.FloatField(default=0.0)),
                ('min_alt', models.FloatField(default=0.0)),
                ('max_alt', models.FloatField(default=0.0)),
                ('roughness', models.FloatField(default=0.0)),
                ('air_density', models.FloatField(default=0.0)),
                ('power_avg', models.FloatField(default=0.0)),
                ('land_type', models.CharField(blank=True, max_length=50)),
                ('potential', models.FloatField(default=0.0)),
                ('zone_index', models.IntegerField(default=0)),
                ('A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_A', to='analysis.point')),
                ('B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_B', to='analysis.point')),
                ('C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_C', to='analysis.point')),
                ('D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_D', to='analysis.point')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='analysis.regiongrid')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.infrastructure')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='max_potential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_in_region', to='analysis.zone'),
        ),
        migrations.AddConstraint(
            model_name='regiongrid',
            constraint=models.UniqueConstraint(fields=('region', 'side_km', 'zones_per_edge'), name='unique_region_grid_config'),
        ),
    ]
