# Generated by Django 5.2.8 on 2025-11-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.infrastructure'),
        ),
    ]
