# Generated by Django 5.2.8 on 2025-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='index_average',
        ),
        migrations.RemoveField(
            model_name='region',
            name='infrastructure_rating',
        ),
        migrations.RemoveField(
            model_name='region',
            name='max_potential',
        ),
        migrations.RemoveField(
            model_name='region',
            name='rating',
        ),
        migrations.AlterField(
            model_name='zone',
            name='land_type',
            field=models.JSONField(default=dict),
        ),
    ]
