# Generated by Django 5.2.8 on 2025-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='wind_direction',
            field=models.FloatField(default=0.0),
        ),
    ]
