# Generated by Django 5.2.8 on 2025-12-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_region_index_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='infrastructure',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='land_type',
            new_name='land_usage',
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
    ]
