# Generated by Django 5.2.8 on 2025-11-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_zone_wind_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiongrid',
            name='A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_A', to='analysis.point'),
        ),
        migrations.AddField(
            model_name='regiongrid',
            name='B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_B', to='analysis.point'),
        ),
        migrations.AddField(
            model_name='regiongrid',
            name='C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_C', to='analysis.point'),
        ),
        migrations.AddField(
            model_name='regiongrid',
            name='D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_D', to='analysis.point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='infrastructure_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='region',
            name='wind_rose',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='zone',
            name='max_alt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='min_alt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='roughness',
            field=models.FloatField(default=0.0),
        ),
    ]
