# Generated by Django 5.2.8 on 2025-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_zone_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_index',
            field=models.IntegerField(default=0),
        ),
    ]
