# Generated by Django 5.2.8 on 2025-12-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_zone_infrastructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('km_jud', models.IntegerField(default=0)),
                ('km_nat', models.IntegerField(default=0)),
                ('km_euro', models.IntegerField(default=0)),
                ('km_auto', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='zone',
            name='land_usage',
        ),
        migrations.AddField(
            model_name='region',
            name='index_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='region',
            name='infrastructure_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='region',
            name='max_potential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_in_region', to='analysis.zone'),
        ),
        migrations.AddField(
            model_name='region',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='land_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='zone',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.infrastructure'),
        ),
    ]
