# Generated by Django 5.2.8 on 2025-11-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_zone_zone_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='point',
            constraint=models.UniqueConstraint(fields=('lat', 'lon'), name='unique_lat_lon'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('center',), name='unique_region_center'),
        ),
    ]
