# Generated by Django 5.2.8 on 2025-11-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('km_jud', models.IntegerField(default=0)),
                ('km_nat', models.IntegerField(default=0)),
                ('km_euro', models.IntegerField(default=0)),
                ('km_auto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.point')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('wind_rose', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(default=0)),
                ('avg_potential', models.FloatField(default=0.0)),
                ('infrastructure_rating', models.IntegerField(default=0)),
                ('index_average', models.FloatField(default=0.0)),
                ('A', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_A', to='analysis.point')),
                ('B', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_B', to='analysis.point')),
                ('C', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_C', to='analysis.point')),
                ('D', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_D', to='analysis.point')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_center', to='analysis.point')),
                ('closest_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.energystorage')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_alt', models.IntegerField(default=0)),
                ('max_alt', models.IntegerField(default=0)),
                ('roughness', models.IntegerField(default=0)),
                ('air_density', models.FloatField(default=0.0)),
                ('avg_wind_speed', models.FloatField(default=0.0)),
                ('power_avg', models.FloatField(default=0.0)),
                ('land_type', models.CharField(blank=True, max_length=50)),
                ('potential', models.FloatField(default=0.0)),
                ('A', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_A', to='analysis.point')),
                ('B', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_B', to='analysis.point')),
                ('C', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_C', to='analysis.point')),
                ('D', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_D', to='analysis.point')),
                ('infrastructure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.infrastructure')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='analysis.region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='max_potential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_in_region', to='analysis.zone'),
        ),
    ]
